import setuptools

setuptools.setup(name="openml",
                 author="Matthias Feurer",
                 author_email="feurerm@informatik.uni-freiburg.de",
                 maintainer="Matthias Feurer",
                 maintainer_email="feurerm@informatik.uni-freiburg.de",
                 description="Python API for OpenML",
                 license="GPLv3",
                 url="http://openml.org/",
                 version="0.0.1dev",
                 packages=setuptools.find_packages(),
                 package_data={'': ['*.txt', '*.md']},
                 install_requires=["liac-arff>=2.0.2",
                                   "numpy>1.6.2",
                                   "scipy>0.9",
                                   "xmltodict",
                                   "nose"],
                 test_suite="nose.collector",
                 classifiers=['Intended Audience :: Science/Research',
                              'Intended Audience :: Developers',
                              'License :: GPLv3',
                              'Programming Language :: Python',
                              'Topic :: Software Development',
                              'Topic :: Scientific/Engineering',
                              'Operating System :: POSIX',
                              'Operating System :: Unix',
                              'Operating System :: MacOS',
                              'Programming Language :: Python :: 2',
                              'Programming Language :: Python :: 2.7',
                              'Programming Language :: Python :: 3',
                              'Programming Language :: Python :: 3.3',
                              'Programming Language :: Python :: 3.4',
                 ])