name: pre-commit

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - develop
    tags:
      - "v*.*.*"

  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-all-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install
    - name: Run pre-commit
      run: |
        pre-commit run --all-files
