name: Tests

on: [push, pull_request]

jobs:
  ubuntu:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        scikit-learn: [0.21.2, 0.22.2, 0.23.1]
        exclude:
          - python-version: 3.8
            scikit-learn: 0.21.2
        include:
          - python-version: 3.6
            scikit-learn: 0.18.2
            scipy: 1.2.0
          - python-version: 3.6
            scikit-learn: 0.19.2
          - python-version: 3.6
            scikit-learn: 0.20.2
          - python-version: 3.8
            scikit-learn: 0.23.1
            code-cov: true
      fail-fast:  false
      max-parallel: 4

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Install scikit-learn ${{ matrix.scikit-learn }}
      run: |
        pip install scikit-learn==${{ matrix.scikit-learn }}
    - name: Install scipy ${{ matrix.scipy }}
      if: ${{ matrix.scipy }}
      run: |
        pip install scipy==${{ matrix.scipy }}
    - name: Run tests
      run: |
        if [ ${{ matrix.code-cov }} ]; then codecov='--cov=openml --long  --cov-report=xml'; fi
        pytest -n 4 --durations=20 --timeout=600 --timeout-method=thread -sv $codecov
    - name: Upload coverage
      if: ${{ matrix.code-cov }} && ${{ always() }}
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        verbose: true
